apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: bookinfo-common-config
spec:
  git:
    type: github
    apiUrl: 
    repository: tmax-cloud/bookinfo-common
    token:
      valueFrom:
        secretKeyRef:
          name: yxzzzxh-git-token
          key: token
  jobs:
    postSubmit:
      - name: gradle-build-and-publish
        image: docker.io/gradle:7.3.1-jdk11
        script: |
          gradle build
          gradle publish
        when:
          tag:
            - v.*
      
